### Vehicle Re-ID Gate - MATCH requests
### Requires the "REST Client" VS Code extension (humao.rest-client) to run inline.
### Images are read from ../dataset/test
### Expected outcome per filename:
###   match-ANV363.jpeg -> MATCH, licensePlate = ANV363
###   match-PJM609.jpeg -> MATCH, licensePlate = PJM609
###   match-RGH433.jpeg -> MATCH, licensePlate = RGH433
###   no-match.jpeg      -> NO_MATCH (no enrolled vehicle should score above threshold)

@baseUrl = http://localhost:5000

### 1) Match against ANV363
POST {{baseUrl}}/api/reid/match HTTP/1.1
Content-Type: multipart/form-data; boundary=----ReIdBoundaryMatchANV363

------ReIdBoundaryMatchANV363
Content-Disposition: form-data; name="TopK"

5
------ReIdBoundaryMatchANV363
Content-Disposition: form-data; name="Images"; filename="match-ANV363.jpeg"
Content-Type: image/jpeg

< ../dataset/test/match-ANV363.jpeg
------ReIdBoundaryMatchANV363--

### 2) Match against PJM609
POST {{baseUrl}}/api/reid/match HTTP/1.1
Content-Type: multipart/form-data; boundary=----ReIdBoundaryMatchPJM609

------ReIdBoundaryMatchPJM609
Content-Disposition: form-data; name="TopK"

5
------ReIdBoundaryMatchPJM609
Content-Disposition: form-data; name="Images"; filename="match-PJM609.jpeg"
Content-Type: image/jpeg

< ../dataset/test/match-PJM609.jpeg
------ReIdBoundaryMatchPJM609--

### 3) Match against RGH433
POST {{baseUrl}}/api/reid/match HTTP/1.1
Content-Type: multipart/form-data; boundary=----ReIdBoundaryMatchRGH433

------ReIdBoundaryMatchRGH433
Content-Disposition: form-data; name="TopK"

5
------ReIdBoundaryMatchRGH433
Content-Disposition: form-data; name="Images"; filename="match-RGH433.jpeg"
Content-Type: image/jpeg

< ../dataset/test/match-RGH433.jpeg
------ReIdBoundaryMatchRGH433--

### 4) Match with no expected match
POST {{baseUrl}}/api/reid/match HTTP/1.1
Content-Type: multipart/form-data; boundary=----ReIdBoundaryMatchNoMatch

------ReIdBoundaryMatchNoMatch
Content-Disposition: form-data; name="TopK"

5
------ReIdBoundaryMatchNoMatch
Content-Disposition: form-data; name="Images"; filename="no-match.jpeg"
Content-Type: image/jpeg

< ../dataset/test/no-match.jpeg
------ReIdBoundaryMatchNoMatch--
